name: Playwright CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Install Playwright browsers
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # 5️⃣ Run Playwright tests with HTML report
      - name: Run Playwright tests
        run: npx playwright test --reporter=html

      # 6️⃣ Upload Playwright HTML report as artifact
      - name: Upload Playwright Test Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/

      # 7️⃣ Deploy report to GitHub Pages
      - name: Deploy HTML report to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright-report
